### ISSUE TITLE
Error - Failed to Load Icon Pack List

### ISSUE THREAD

**Issue by corinnekaryiu** [aidenlx/obsidian-icon-shortcodes#36]
While on mobile, I get this error when I click on "Browser":

```
Failed to Load Icon Pack List:
(0, li.requestUrl) is not a function
```

Also, if I try to restore icons from a backup, it crashes Obsidian.

**Comment by aidenlx** [comment]
What version of mobile obsidian are you using? make sure you've update to the latest since the plugin depend on some new API.

**Comment by corinnekaryiu** [comment]
Thanks for the quick response. I'm using the latest Android version, though this was last updated on 4th Feb and only incorporates functionality up to desktop v0.13.24.

**Comment by corinnekaryiu** [comment]
This now works with the latest mobile release (v1.1.1) so I'm closing this!
